//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Generation {
		public class Gate {
		
		public int x1 = 0;
		public int y1 = 0;

		public int x2 = 0;
		public int y2 = 0;

		public int HigherLevel = 0;

				public Gate () {


				}
		}
}

